package model;

import java.math.BigDecimal;

public class DiscountBO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cy_bt_Dsc_Info.Dsc_Name
     *
     * @mbggenerated
     */
    private String dsc_Name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cy_bt_Dsc_Info.Type_Id
     *
     * @mbggenerated
     */
    private String type_Id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cy_bt_Dsc_Info.Type_Name
     *
     * @mbggenerated
     */
    private String type_Name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cy_bt_Dsc_Info.DscVal
     *
     * @mbggenerated
     */
    private BigDecimal dscVal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cy_bt_Dsc_Info.Dsc_Name
     *
     * @return the value of cy_bt_Dsc_Info.Dsc_Name
     *
     * @mbggenerated
     */
    public String getDsc_Name() {
        return dsc_Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cy_bt_Dsc_Info.Dsc_Name
     *
     * @param dsc_Name the value for cy_bt_Dsc_Info.Dsc_Name
     *
     * @mbggenerated
     */
    public void setDsc_Name(String dsc_Name) {
        this.dsc_Name = dsc_Name == null ? null : dsc_Name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cy_bt_Dsc_Info.Type_Id
     *
     * @return the value of cy_bt_Dsc_Info.Type_Id
     *
     * @mbggenerated
     */
    public String getType_Id() {
        return type_Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cy_bt_Dsc_Info.Type_Id
     *
     * @param type_Id the value for cy_bt_Dsc_Info.Type_Id
     *
     * @mbggenerated
     */
    public void setType_Id(String type_Id) {
        this.type_Id = type_Id == null ? null : type_Id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cy_bt_Dsc_Info.Type_Name
     *
     * @return the value of cy_bt_Dsc_Info.Type_Name
     *
     * @mbggenerated
     */
    public String getType_Name() {
        return type_Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cy_bt_Dsc_Info.Type_Name
     *
     * @param type_Name the value for cy_bt_Dsc_Info.Type_Name
     *
     * @mbggenerated
     */
    public void setType_Name(String type_Name) {
        this.type_Name = type_Name == null ? null : type_Name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cy_bt_Dsc_Info.DscVal
     *
     * @return the value of cy_bt_Dsc_Info.DscVal
     *
     * @mbggenerated
     */
    public BigDecimal getDscVal() {
        return dscVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cy_bt_Dsc_Info.DscVal
     *
     * @param dscVal the value for cy_bt_Dsc_Info.DscVal
     *
     * @mbggenerated
     */
    public void setDscVal(BigDecimal dscVal) {
        this.dscVal = dscVal;
    }
}