package model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class DiscountBOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cy_bt_Dsc_Info
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cy_bt_Dsc_Info
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cy_bt_Dsc_Info
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    private Integer limit;

    private Integer offset;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cy_bt_Dsc_Info
     *
     * @mbggenerated
     */
    public DiscountBOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cy_bt_Dsc_Info
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cy_bt_Dsc_Info
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cy_bt_Dsc_Info
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cy_bt_Dsc_Info
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cy_bt_Dsc_Info
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cy_bt_Dsc_Info
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cy_bt_Dsc_Info
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cy_bt_Dsc_Info
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cy_bt_Dsc_Info
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cy_bt_Dsc_Info
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return offset;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cy_bt_Dsc_Info
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDsc_NameIsNull() {
            addCriterion("Dsc_Name is null");
            return (Criteria) this;
        }

        public Criteria andDsc_NameIsNotNull() {
            addCriterion("Dsc_Name is not null");
            return (Criteria) this;
        }

        public Criteria andDsc_NameEqualTo(String value) {
            addCriterion("Dsc_Name =", value, "dsc_Name");
            return (Criteria) this;
        }

        public Criteria andDsc_NameNotEqualTo(String value) {
            addCriterion("Dsc_Name <>", value, "dsc_Name");
            return (Criteria) this;
        }

        public Criteria andDsc_NameGreaterThan(String value) {
            addCriterion("Dsc_Name >", value, "dsc_Name");
            return (Criteria) this;
        }

        public Criteria andDsc_NameGreaterThanOrEqualTo(String value) {
            addCriterion("Dsc_Name >=", value, "dsc_Name");
            return (Criteria) this;
        }

        public Criteria andDsc_NameLessThan(String value) {
            addCriterion("Dsc_Name <", value, "dsc_Name");
            return (Criteria) this;
        }

        public Criteria andDsc_NameLessThanOrEqualTo(String value) {
            addCriterion("Dsc_Name <=", value, "dsc_Name");
            return (Criteria) this;
        }

        public Criteria andDsc_NameLike(String value) {
            addCriterion("Dsc_Name like", value, "dsc_Name");
            return (Criteria) this;
        }

        public Criteria andDsc_NameNotLike(String value) {
            addCriterion("Dsc_Name not like", value, "dsc_Name");
            return (Criteria) this;
        }

        public Criteria andDsc_NameIn(List<String> values) {
            addCriterion("Dsc_Name in", values, "dsc_Name");
            return (Criteria) this;
        }

        public Criteria andDsc_NameNotIn(List<String> values) {
            addCriterion("Dsc_Name not in", values, "dsc_Name");
            return (Criteria) this;
        }

        public Criteria andDsc_NameBetween(String value1, String value2) {
            addCriterion("Dsc_Name between", value1, value2, "dsc_Name");
            return (Criteria) this;
        }

        public Criteria andDsc_NameNotBetween(String value1, String value2) {
            addCriterion("Dsc_Name not between", value1, value2, "dsc_Name");
            return (Criteria) this;
        }

        public Criteria andType_IdIsNull() {
            addCriterion("Type_Id is null");
            return (Criteria) this;
        }

        public Criteria andType_IdIsNotNull() {
            addCriterion("Type_Id is not null");
            return (Criteria) this;
        }

        public Criteria andType_IdEqualTo(String value) {
            addCriterion("Type_Id =", value, "type_Id");
            return (Criteria) this;
        }

        public Criteria andType_IdNotEqualTo(String value) {
            addCriterion("Type_Id <>", value, "type_Id");
            return (Criteria) this;
        }

        public Criteria andType_IdGreaterThan(String value) {
            addCriterion("Type_Id >", value, "type_Id");
            return (Criteria) this;
        }

        public Criteria andType_IdGreaterThanOrEqualTo(String value) {
            addCriterion("Type_Id >=", value, "type_Id");
            return (Criteria) this;
        }

        public Criteria andType_IdLessThan(String value) {
            addCriterion("Type_Id <", value, "type_Id");
            return (Criteria) this;
        }

        public Criteria andType_IdLessThanOrEqualTo(String value) {
            addCriterion("Type_Id <=", value, "type_Id");
            return (Criteria) this;
        }

        public Criteria andType_IdLike(String value) {
            addCriterion("Type_Id like", value, "type_Id");
            return (Criteria) this;
        }

        public Criteria andType_IdNotLike(String value) {
            addCriterion("Type_Id not like", value, "type_Id");
            return (Criteria) this;
        }

        public Criteria andType_IdIn(List<String> values) {
            addCriterion("Type_Id in", values, "type_Id");
            return (Criteria) this;
        }

        public Criteria andType_IdNotIn(List<String> values) {
            addCriterion("Type_Id not in", values, "type_Id");
            return (Criteria) this;
        }

        public Criteria andType_IdBetween(String value1, String value2) {
            addCriterion("Type_Id between", value1, value2, "type_Id");
            return (Criteria) this;
        }

        public Criteria andType_IdNotBetween(String value1, String value2) {
            addCriterion("Type_Id not between", value1, value2, "type_Id");
            return (Criteria) this;
        }

        public Criteria andType_NameIsNull() {
            addCriterion("Type_Name is null");
            return (Criteria) this;
        }

        public Criteria andType_NameIsNotNull() {
            addCriterion("Type_Name is not null");
            return (Criteria) this;
        }

        public Criteria andType_NameEqualTo(String value) {
            addCriterion("Type_Name =", value, "type_Name");
            return (Criteria) this;
        }

        public Criteria andType_NameNotEqualTo(String value) {
            addCriterion("Type_Name <>", value, "type_Name");
            return (Criteria) this;
        }

        public Criteria andType_NameGreaterThan(String value) {
            addCriterion("Type_Name >", value, "type_Name");
            return (Criteria) this;
        }

        public Criteria andType_NameGreaterThanOrEqualTo(String value) {
            addCriterion("Type_Name >=", value, "type_Name");
            return (Criteria) this;
        }

        public Criteria andType_NameLessThan(String value) {
            addCriterion("Type_Name <", value, "type_Name");
            return (Criteria) this;
        }

        public Criteria andType_NameLessThanOrEqualTo(String value) {
            addCriterion("Type_Name <=", value, "type_Name");
            return (Criteria) this;
        }

        public Criteria andType_NameLike(String value) {
            addCriterion("Type_Name like", value, "type_Name");
            return (Criteria) this;
        }

        public Criteria andType_NameNotLike(String value) {
            addCriterion("Type_Name not like", value, "type_Name");
            return (Criteria) this;
        }

        public Criteria andType_NameIn(List<String> values) {
            addCriterion("Type_Name in", values, "type_Name");
            return (Criteria) this;
        }

        public Criteria andType_NameNotIn(List<String> values) {
            addCriterion("Type_Name not in", values, "type_Name");
            return (Criteria) this;
        }

        public Criteria andType_NameBetween(String value1, String value2) {
            addCriterion("Type_Name between", value1, value2, "type_Name");
            return (Criteria) this;
        }

        public Criteria andType_NameNotBetween(String value1, String value2) {
            addCriterion("Type_Name not between", value1, value2, "type_Name");
            return (Criteria) this;
        }

        public Criteria andDscValIsNull() {
            addCriterion("DscVal is null");
            return (Criteria) this;
        }

        public Criteria andDscValIsNotNull() {
            addCriterion("DscVal is not null");
            return (Criteria) this;
        }

        public Criteria andDscValEqualTo(BigDecimal value) {
            addCriterion("DscVal =", value, "dscVal");
            return (Criteria) this;
        }

        public Criteria andDscValNotEqualTo(BigDecimal value) {
            addCriterion("DscVal <>", value, "dscVal");
            return (Criteria) this;
        }

        public Criteria andDscValGreaterThan(BigDecimal value) {
            addCriterion("DscVal >", value, "dscVal");
            return (Criteria) this;
        }

        public Criteria andDscValGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("DscVal >=", value, "dscVal");
            return (Criteria) this;
        }

        public Criteria andDscValLessThan(BigDecimal value) {
            addCriterion("DscVal <", value, "dscVal");
            return (Criteria) this;
        }

        public Criteria andDscValLessThanOrEqualTo(BigDecimal value) {
            addCriterion("DscVal <=", value, "dscVal");
            return (Criteria) this;
        }

        public Criteria andDscValIn(List<BigDecimal> values) {
            addCriterion("DscVal in", values, "dscVal");
            return (Criteria) this;
        }

        public Criteria andDscValNotIn(List<BigDecimal> values) {
            addCriterion("DscVal not in", values, "dscVal");
            return (Criteria) this;
        }

        public Criteria andDscValBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DscVal between", value1, value2, "dscVal");
            return (Criteria) this;
        }

        public Criteria andDscValNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DscVal not between", value1, value2, "dscVal");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cy_bt_Dsc_Info
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cy_bt_Dsc_Info
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}